name: '2048 Docker Image CI'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image

    uses: docker/login-action@v1
    with:
    registry: ghcr.io
    username: ${{ szirszi }}
    password: ${{ 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 }}
    name: Build the 2048 Docker image
      run: |
           docker build . --file Dockerfile --tag ghcr.io/szirszi/2048:latest
           docker run ghcr.io/szirszi/2048:latest
           docker push ghcr.io/szirszi/2048:latest
